ekf_filter_node:
  ros__parameters:
    frequency: 30.0                # Frekuensi update EKF dalam Hz
    sensor_timeout: 0.1            # Timeout sensor dalam detik

    two_d_mode: true               # Mode 2D untuk robot darat (hanya posisi x, y, dan yaw)
    publish_tf: true               # Publikasikan transformasi TF

    # Konfigurasi IMU
    imu0: /imu                     # Sumber data IMU dari topik /imu
    imu0_config: [false, false, false,   # Posisi (tidak digunakan)
                  false, false, true,    # Orientasi yaw (aktif)
                  false, false, false,   # Kecepatan linear (tidak digunakan)
                  false, false, true,    # Kecepatan angular yaw (aktif)
                  false, false, false]   # Percepatan linear
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10

    # Konfigurasi Odometry
    odom0: /odom                   # Sumber data odometry dari topik /odom
    odom0_config: [true, true, false,  # Posisi x dan y (aktif)
                   false, false, true,  # Orientasi yaw (aktif)
                   true, true, false,   # Kecepatan linear x dan y (aktif)
                   false, false, true]  # Kecepatan angular yaw (aktif)
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # Konfigurasi LIDAR (Estimasi Pose dari LIDAR)
    pose0: /scan    # Sumber data pose dari LIDAR
    pose0_config: [true, true, false,  # Posisi x dan y (aktif)
                   false, false, true,  # Orientasi yaw (aktif)
                   false, false, false, # Kecepatan linear (tidak digunakan)
                   false, false, false] # Kecepatan angular (tidak digunakan)
    pose0_queue_size: 10
    pose0_relative: false
    pose0_differential: false

    # Matriks Noise Proses
    # process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
    #                            0, 0.05, 0, 0, 0, 0,
    #                            0, 0, 0.05, 0, 0, 0,
    #                            0, 0, 0, 0.05, 0, 0,
    #                            0, 0, 0, 0, 0.05, 0,
    #                            0, 0, 0, 0, 0, 0.05]

    # # Matriks Estimasi Awal
    # initial_estimate_covariance: [0.1, 0, 0, 0, 0, 0,
    #                               0, 0.1, 0, 0, 0, 0,
    #                               0, 0, 0.1, 0, 0, 0,
    #                               0, 0, 0, 0.1, 0, 0,
    #                               0, 0, 0, 0, 0.1, 0,
    #                               0, 0, 0, 0, 0, 0.1]

    # # Kovariansi Sensor
    # imu0_orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    # imu0_angular_velocity_covariance: [0.05, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.05]
    # odom0_pose_covariance: [0.1,0.0,0.0,0.0,0.0,0.0,
    #                        0.0, 0.1,0.0,0.0,0.0,0.0,
    #                        0.0,0.0, 0.1,0.0,0.0, 0]
    # odom0_twist_covariance: [0.1,0.0,0.0,0.0,0.0, 0,
    #                          0, 0.1, 0, 0, 0, 0,
    #                          0, 0, 0.1, 0, 0, 0]
    # pose0_pose_covariance: [0.1, 0, 0, 0, 0, 0,
    #                         0, 0.1, 0, 0, 0, 0,
    #                         0, 0, 0.1, 0, 0, 0]
