ekf_filter_node:
  ros__parameters:
    frequency: 50.0                 # Frekuensi update filter EKF dalam Hz
    sensor_timeout: 0.1             # Timeout sensor dalam detik

    two_d_mode: true                # Mode 2D untuk robot darat (hanya x, y, dan yaw)
    publish_tf: false               # Nonaktifkan transformasi karena hanya filtering data IMU

    imu0: /imu                      # Sumber data dari topik IMU
    imu0_config: [false, false, false,  # Posisi (tidak digunakan)
                  false, false, true,   # Orientasi yaw (aktif)
                  false, false, false,  # Kecepatan linear (tidak digunakan)
                  false, false, true,   # Kecepatan angular yaw (aktif)
                  true, true, true]  # Percepatan linear (tidak digunakan)
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    imu0_angular_velocity_covariance: [0.05, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0, 0.05]

    # process_noise_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # initial_estimate_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

